# Generated by Django 4.1.13 on 2025-09-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentwebhook",
            name="event_data",
            field=models.JSONField(
                blank=True, help_text="Raw event data from Stripe", null=True
            ),
        ),
    ]
