# Generated by Django 4.1.13 on 2025-09-01 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_paymentwebhook_event_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrefund",
            name="notes",
            field=models.TextField(
                blank=True, help_text="Additional notes about the refund", null=True
            ),
        ),
    ]
