# Generated by Django 4.1.13 on 2025-09-02 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("payments", "0003_paymentrefund_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentrefund",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who processed the refund",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="processed_refunds",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
