# Generated by Django 4.1.13 on 2025-09-02 04:55

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_paymentrefund_processed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('payment_attempt', 'Payment Attempt'), ('payment_success', 'Payment Success'), ('payment_failure', 'Payment Failure'), ('refund_success', 'Refund Success'), ('refund_failure', 'Refund Failure'), ('webhook_received', 'Webhook Received')], help_text='Type of payment metric event', max_length=20)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Payment amount (if applicable)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', help_text='ISO currency code', max_length=3)),
                ('metadata', models.JSONField(default=dict, help_text='Additional metric metadata (processing time, error codes, etc.)')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='When this metric event occurred')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payment Metric',
                'verbose_name_plural': 'Payment Metrics',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentmetric',
            index=models.Index(fields=['event_type', 'timestamp'], name='payments_pa_event_t_ca0524_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmetric',
            index=models.Index(fields=['timestamp'], name='payments_pa_timesta_879a00_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentmetric',
            index=models.Index(fields=['currency', 'timestamp'], name='payments_pa_currenc_fd1ea9_idx'),
        ),
    ]
