# Generated by Django 4.1.13 on 2025-09-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="payment_type",
            field=models.CharField(
                choices=[
                    ("CASH", "CASH"),
                    ("DEBIT/CREDIT", "DEBIT/CREDIT"),
                    ("EBT", "EBT"),
                    ("STRIPE", "STRIPE"),
                ],
                editable=False,
                max_length=32,
            ),
        ),
    ]
